name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Disable native C++ build
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          sed -i '/externalNativeBuild/d' app/build.gradle* || true
          sed -i '/ndkBuild/d' app/build.gradle* || true
          
      - name: Build pure WireGuard APK
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleFdroidDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my_warp_vpn
          path: app/build/outputs/apk/fdroid/debug/*.apk
